// รูป unit ของ Anime Expeditions ดึงจาก wiki (CC BY-SA 4.0, https://wiki.animeexpeditions.com/Units)
// เก็บเป็นไฟล์ local ใน `public/ae-units/` — key = Asset id ในเกม (เช่น SaboEVO) -> path รูป local
// วิธี regen: รันสคริปต์ดึงจาก wiki API (`/w/api.php?prop=pageimages`) แล้วเซฟเป็น public/ae-units/<asset-lower>.png
// unit ที่ไม่มีหน้า wiki (Damu/Goose/Jace/Turret/Cube/...) ไม่มี entry — component โชว์ตัวอักษรแทน
export const AE_UNIT_IMAGE_MAP: Record<string, string> = {
  "Ban": "/ae-units/ban.png?v=3", // Greed
  "Cell": "/ae-units/cell.png?v=3", // Bioinsect
  "CellEVO": "/ae-units/cellevo.png?v=3", // Bioinsect (Final Form)
  "Choso": "/ae-units/choso.png?v=3", // Crimson
  "ChosoEVO": "/ae-units/chosoevo.png?v=3", // Crimson (Brother)
  "Crocodile": "/ae-units/crocodile.png?v=3", // Sand
  "CrocodileEVO": "/ae-units/crocodileevo.png?v=3", // Sand (Alligator)
  "Diane": "/ae-units/diane.png?v=3", // Lady Giant
  "DianeEVO": "/ae-units/dianeevo.png?v=3", // Lady Giant (Envy)
  "Doflamingo": "/ae-units/doflamingo.png?v=3", // String Demon
  "DoflamingoEVO": "/ae-units/doflamingoevo.png?v=3", // String Demon (Awakened)
  "Enel": "/ae-units/enel.png?v=3", // Lightning God
  "EnelEVO": "/ae-units/enelevo.png?v=3", // Lightning God (Overcharged)
  "Frieren": "/ae-units/frieren.png?v=3", // Elf Mage
  "FrierenEVO": "/ae-units/frierenevo.png?v=3", // Elf Mage (Unleashed)
  "Gabimaru": "/ae-units/gabimaru.png?v=3", // Hollow
  "GabimaruEVO": "/ae-units/gabimaruevo.png?v=3", // Hollow (Blaze)
  "Genos": "/ae-units/genos.png?v=3", // Demon Cyborg
  "Gohan": "/ae-units/gohan.png?v=3", // Prodigy
  "GohanEVO": "/ae-units/gohanevo.png?v=3", // Prodigy (Rage)
  "Goku": "/ae-units/goku.png?v=3", // Little Carrot
  "GokuSS1": "/ae-units/gokuss1.png?v=3", // Carrot
  "GokuSS1EVO": "/ae-units/gokuss1evo.png?v=3", // Carrot (Unleashed)
  "Gon": "/ae-units/gon.png?v=3", // Nen Hunter
  "Gowther": "/ae-units/gowther.png?v=3", // Puppet
  "GowtherEVO": "/ae-units/gowtherevo.png?v=3", // Puppet (Telekinetic)
  "Gray": "/ae-units/gray.png?v=3", // Ice Mage
  "Griffith": "/ae-units/griffith.png?v=3", // Broken Falcon
  "GriffithFemto": "/ae-units/griffithfemto.png?v=3", // 5th God Hand
  "GriffithSilver": "/ae-units/griffithsilver.png?v=3", // Silver Falcon
  "Grimmjow": "/ae-units/grimmjow.png?v=3", // Razorjaw
  "GrimmjowEVO": "/ae-units/grimmjowevo.png?v=3", // Razorjaw (Hunter)
  "Guts": "/ae-units/guts.png?v=3", // Iron Wolf
  "GutsEVO": "/ae-units/gutsevo.png?v=3", // Iron Wolf (Struggler)
  "Harribel": "/ae-units/harribel.png?v=3", // Sharkfang
  "HarribelEVO": "/ae-units/harribelevo.png?v=3", // Sharkfang (Abyssal)
  "HimmelTheHero": "/ae-units/himmelthehero.png?v=3", // The Hero
  "Hinata": "/ae-units/hinata.png?v=3", // True Saint
  "HinataEVO": "/ae-units/hinataevo.png?v=3", // True Saint (Holy)
  "Ichigo": "/ae-units/ichigo.png?v=3", // Reaper
  "IchigoEVO": "/ae-units/ichigoevo.png?v=3", // Reaper (Released)
  "Ichiraku": "/ae-units/ichiraku.png?v=3", // Ramen Guy
  "Inumaki": "/ae-units/inumaki.png?v=3", // Salmon Sorcerer
  "InumakiEVO": "/ae-units/inumakievo.png?v=3", // Salmon Sorcerer (Grade 1)
  "Itachi": "/ae-units/itachi.png?v=3", // Crow
  "ItachiEVO": "/ae-units/itachievo.png?v=3", // Crow (Black Fire)
  "Judar": "/ae-units/judar.png?v=3", // Dark Mage
  "JudarEVO": "/ae-units/judarevo.png?v=3", // Dark Mage (Sovereign)
  "Kenpachi": "/ae-units/kenpachi.png?v=3", // 8th Sword
  "KenpachiEVO": "/ae-units/kenpachievo.png?v=3", // 8th Sword (Berserk)
  "Khun": "/ae-units/khun.png?v=3", // Cubert
  "KhunCube": "/ae-units/khuncube.png?v=3", // Cube
  "Killua": "/ae-units/killua.png?v=3", // Kid Assassin
  "Kite": "/ae-units/kite.png?v=3", // Jester
  "Levi": "/ae-units/levi.png?v=3", // Corps Captain
  "Luffy": "/ae-units/luffy.png?v=3", // Rubber Boy
  "Megumi": "/ae-units/megumi.png?v=3", // Shadow
  "MegumiEVO": "/ae-units/megumievo.png?v=3", // Shadow (Divine)
  "MegumiMahoraga": "/ae-units/megumimahoraga.png?v=3", // Spirit General (Divine)
  "MegumiNue": "/ae-units/meguminue.png?v=3", // Winged Spirit (Divine)
  "Noelle": "/ae-units/noelle.png?v=3", // Water Princess
  "Riyo": "/ae-units/riyo.png?v=3", // Scissor
  "Rukia": "/ae-units/rukia.png?v=3", // Ice Queen
  "Sabo": "/ae-units/sabo.png?v=3", // Flame Emperor
  "SaboEVO": "/ae-units/saboevo.png?v=3", // Flame Emperor (Reincarnate)
  "Sanji": "/ae-units/sanji.png?v=3", // Curly Brow
  "Sasuke": "/ae-units/sasuke.png?v=3", // Thunder Shinobi
  "Senku": "/ae-units/senku.png?v=3", // Stone Alchemist
  "Sinbad": "/ae-units/sinbad.png?v=3", // Sovereign
  "SinbadEVO": "/ae-units/sinbadevo.png?v=3", // Sovereign (Djinn)
  "SkullKnight": "/ae-units/skullknight.png?v=3", // Eclipse Hunter
  "SkullKnightEVO": "/ae-units/skullknightevo.png?v=3", // Eclipse Hunter (Savior)
  "Sparkle": "/ae-units/sparkle.png?v=3", // Kitsune
  "Sugar": "/ae-units/sugar.png?v=3", // Toy Maker
  "Trunks": "/ae-units/trunks.png?v=3", // The Drink
  "TrunksEVO": "/ae-units/trunksevo.png?v=3", // The Drink (Juicebox)
  "Uryu": "/ae-units/uryu.png?v=3", // Reishi Archer
  "Utahime": "/ae-units/utahime.png?v=3", // Forbidden Teacher
  "Vegeta": "/ae-units/vegeta.png?v=3", // Vegetable
  "VegetaEVO": "/ae-units/vegetaevo.png?v=3", // Vegetable (Prince)
  "WaterMagician": "/ae-units/watermagician.png?v=3", // Water Mage
  "WaterMagicianEVO": "/ae-units/watermagicianevo.png?v=3", // Water Mage (Scholar)
  "Weather": "/ae-units/weather.png?v=3", // Rainman
  "WeatherEVO": "/ae-units/weatherevo.png?v=3", // Rainman (Forecast)
  "Yamamoto": "/ae-units/yamamoto.png?v=3", // Head Captain
  "YamamotoEVO": "/ae-units/yamamotoevo.png?v=3", // Head Captain (Char)
  "Yuta": "/ae-units/yuta.png?v=3", // Cursed Student
  "YutaEVO": "/ae-units/yutaevo.png?v=3", // Cursed Student (True Love)
  "Zeref": "/ae-units/zeref.png?v=3", // Cursed Immortal
  "ZerefEVO": "/ae-units/zerefevo.png?v=3", // Cursed Immortal (Black Sun)
  "Zoro": "/ae-units/zoro.png?v=3", // Bounty Hunter
};

export function aeUnitImageFor(asset?: string | null): string | null {
  if (!asset) return null;
  return AE_UNIT_IMAGE_MAP[asset] ?? null;
}
